
spring:
  datasource.type: com.zaxxer.hikari.HikariDataSource
  application:
    name: database-app
  dbprofileservice:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.2:3306/PROFILESERVICE"
    jdbc-url: "jdbc:mysql://127.0.0.2:3306/PROFILESERVICE"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000

  dbTaskService:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.3:3306/TASKSERVICE"
    jdbc-url: "jdbc:mysql://127.0.0.3:3306/TASKSERVICE"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1    
    max-active: 15
    max-idle: 10
    max-wait: 8000
server:
  port: 8088
